[Network]
selected_networks = ["BASE_SEPOLIA"]

# soak test specific configuration
[Soak.Common]
chainlink_node_funding = 0.5 # Funding per node

[Soak.OCR2]
[Soak.OCR2.Common]
test_duration = "24h" # Full duration the test will run 1440 - 1 day, 7200 - 5 days

[Soak.OCR2.Soak]
number_of_contracts = 2    # Number of deployed contracts, 2 being default
time_between_rounds = "5m" # Default 5 mins for a 1 day, 10 mins for a 5 day

[Seth]
experiments_enabled = ["slow_funds_return"]
